server:
  port: 8080

spring:
  application:
    name: auth-service

app:
  version: v202308201929

feign:
  client:
    config:
      identityService:
        url: ${IDENTITY_SERVICE_URL:http://localhost:8081}
