server:
  port: 8080

spring:
  application:
    name: identity-service
  datasource:
    url:
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  version: v20230629
