server:
  port: 8080

spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://localhost:5432/locked_out
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  version: v20230628