apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service-depl
  labels:
    app: identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
      - name: identity-service
        image: abulsy3d/locked-out-identity-service:v202307012222
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://51.140.227.135:5432/locked_out
        - name: SPRING_DATASOURCE_USERNAME
          value: admin
        - name: SPRING_DATASOURCE_PASSWORD
          value: admin
        - name: SPLUNK_URL
          value: http://51.140.228.65:8088
        - name: SPLUNK_TOKEN
          value: 73fa0f6d-b98b-43c6-8c49-906844a2213f
        - name: SPLUNK_INDEX
          value: identity_service_api
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  selector:
    app: identity-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081