apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service-depl
  labels:
    app: identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
      - name: identity-service
        image: abulsy3d/locked-out-identity-service:v202401021936
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://51.142.177.163:5432/locked_out
        - name: SPRING_DATASOURCE_USERNAME
          value: admin
        - name: SPRING_DATASOURCE_PASSWORD
          value: admin
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          value: xxxxx
        # - name: SPLUNK_URL
        #   value: http://51.142.141.163:8088
        # - name: SPLUNK_TOKEN
        #   value: f82c5b71-b9a9-44f3-ae1e-47923bd6f0e6
        # - name: SPLUNK_INDEX
        #   value: identity_service_api
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  selector:
    app: identity-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081