version: "3"

services:
  postgres-db:
    image: postgres:14.2-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    restart: always

  identity-service:
    build: ../identity-service
    container_name: identity-service
    ports:
      - 8081:8081
    environment:
      # SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres-db
    restart: always

  auth-service:
    build: ../auth-service
    container_name: auth-service
    ports:
      - 8080:8080
    # environment:
      # SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - identity-service
    restart: always

  frontend:
    build: ../frontend
    container_name: frontend
    ports:
      - 3000:3000
    # environment:
      # VITE_SOME_KEY: hello world
    depends_on:
      - identity-service
    restart: always