version: "3"

services:
  postgres-db:
    image: postgres:14.2-alpine
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=locked_out
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    restart: always

  # migrated to app insights
  # splunk-8.2:
  #   image: splunk/splunk:8.2
  #   container_name: splunk-8.2
  #   ports:
  #     - 8000:8000 # UI
  #     - 8088:8088 # HTTP event collector
  #   environment:
  #     SPLUNK_START_ARGS: --accept-license
  #     SPLUNK_PASSWORD: splunk123

  identity-service:
    build: ../identity-service
    container_name: identity-service
    ports:
      - 8081:8081
    environment:
      # SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/locked_out
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      # SPLUNK_URL: http://splunk-8.2:8088
      # SPLUNK_TOKEN: 25b8746e-9100-4d44-80fc-bd6989759a45
      # SPLUNK_INDEX: identity_service_api
      APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=a2b305e0-a7ef-4148-8c41-80d2e7b0890d;IngestionEndpoint=https://ukwest-0.in.applicationinsights.azure.com/;LiveEndpoint=https://ukwest.livediagnostics.monitor.azure.com/"
    depends_on:
      - postgres-db
      # - splunk-8.2
    restart: always

  auth-service:
    build: ../auth-service
    container_name: auth-service
    ports:
      - 8080:8080
    environment:
      # SPRING_PROFILES_ACTIVE: dev
      # SPLUNK_URL: http://splunk-8.2:8088
      # SPLUNK_TOKEN: 5fabb82e-7466-4122-b17f-408bb8190f67
      # SPLUNK_INDEX: auth_service_api
      APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=a2b305e0-a7ef-4148-8c41-80d2e7b0890d;IngestionEndpoint=https://ukwest-0.in.applicationinsights.azure.com/;LiveEndpoint=https://ukwest.livediagnostics.monitor.azure.com/"
    depends_on:
      - identity-service
      # - splunk-8.2
    restart: always

  frontend:
    build: ../frontend
    container_name: frontend
    ports:
      - 3000:3000
    environment:
      VITE_IDENTITY_SERVICE_HOST: http://localhost:8081
    depends_on:
      - identity-service
    restart: always

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - 9000:9000
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres-db:5432/locked_out
      SONARQUBE_JDBC_USERNAME: admin
      SONARQUBE_JDBC_PASSWORD: admin
    depends_on:
      - postgres-db
    restart: always

  pact-broker:
    image: pactfoundation/pact-broker
    container_name: pact-broker
    ports:
      - 9292:9292
    environment:
      PACT_BROKER_DATABASE_HOST: postgres-db
      PACT_BROKER_DATABASE_USERNAME: admin
      PACT_BROKER_DATABASE_PASSWORD: admin
      PACT_BROKER_DATABASE_NAME: locked_out
      PACT_BROKER_LOG_LEVEL: DEBUG
    depends_on:
      - postgres-db
    restart: always