version: "3"

services:
  postgres-db:
    image: postgres:14.2-alpine
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    restart: always

  splunk-8.2:
    image: splunk/splunk:8.2
    container_name: splunk-8.2
    ports:
      - 8000:8000
      - 8088:8088
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: splunk123

  identity-service:
    build: ../identity-service
    container_name: identity-service
    ports:
      - 8081:8081
    environment:
      # SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPLUNK_URL: http://splunk-8.2:8088
      SPLUNK_TOKEN: 25b8746e-9100-4d44-80fc-bd6989759a45
      SPLUNK_INDEX: identity_service_api
    depends_on:
      - postgres-db
    restart: always

  auth-service:
    build: ../auth-service
    container_name: auth-service
    ports:
      - 8080:8080
    environment:
      # SPRING_PROFILES_ACTIVE: dev
      SPLUNK_URL: http://splunk-8.2:8088
      SPLUNK_TOKEN: 5fabb82e-7466-4122-b17f-408bb8190f67
      SPLUNK_INDEX: auth_service_api
    depends_on:
      - identity-service
    restart: always

  # frontend:
  #   build: ../frontend
  #   container_name: frontend
  #   ports:
  #     - 3000:3000
  #   # environment:
  #     # VITE_SOME_KEY: hello world
  #   depends_on:
  #     - identity-service
  #   restart: always