{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.deploymentLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploymentLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentLabel }}
    spec:
      containers:
      - name: {{ .Values.deploymentLabel }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        {{- if .Values.deployment.containerPorts }}
          {{- range .Values.deployment.containerPorts }}
          - containerPort: {{ .containerPort }}
          {{- end }}
        {{- end }}
        env:
        {{- if .Values.deployment.envVars }}
          {{- range .Values.deployment.envVars }}
          - name: {{ .name }}
            value: {{ .value }}
          {{- end }}
        {{- end }}
{{- end -}}