name: auth-service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'auth-service/**'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run Unit Tests
      working-directory: ./auth-service
      run: mvn test

  build_image:
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./auth-service
      run: |
        timestamp=$(TZ="Europe/London" date +'%Y%m%d%H%M')
        tag="v$timestamp"
        docker build . --file Dockerfile --tag abulsy3d/locked-out-auth-service:$tag

  push_image:
    runs-on: ubuntu-latest
    needs: [unit_tests, build_image]
    steps:
    - name: Push the Docker image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u abulsy3d --password-stdin
        docker push abulsy3d/locked-out-auth-service:$tag
