name: auth-service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'auth-service/**'
  pull_request:
#    branches: [ "main" ]
    paths:
      - 'auth-service/**'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run Unit Tests
      working-directory: ./auth-service
      run: ./gradlew test

  integration_tests:
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Integration Tests
        working-directory: ./auth-service
        run: ./gradlew integrationTest

  functional_tests:
    runs-on: ubuntu-latest
    needs: [unit_tests, integration_tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Functional Tests
        working-directory: ./auth-service
        run: ./gradlew functionalTest

  build_and_push_image:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [unit_tests, integration_tests, functional_tests]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build and Push the Docker image
      working-directory: ./auth-service
      run: |
        timestamp=$(TZ="Europe/London" date +'%Y%m%d%H%M')
        tag="v$timestamp"
        docker build . --file Dockerfile --tag abulsy3d/locked-out-auth-service:$tag
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u abulsy3d --password-stdin
        docker push abulsy3d/locked-out-auth-service:$tag