name: frontend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./frontend
      run: |
        timestamp=$(TZ="Europe/London" date +'%Y%m%d%H%M')
        tag="v$timestamp"
        docker build . --file Dockerfile --tag abulsy3d/locked-out-frontend:$tag

  push_image:
    runs-on: ubuntu-latest
    needs: build_image
    steps:
    - name: Push the Docker image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u abulsy3d --password-stdin
        docker push abulsy3d/locked-out-frontend:$tag
