name: identity-service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'identity-service/**'
  pull_request:
#    branches: [ "main" ]
    paths:
      - 'identity-service/**'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run Unit Tests
      working-directory: ./identity-service
      run: ./gradlew test

  integration_tests:
    runs-on: ubuntu-latest
    needs: unit_tests
#    services:
#     postgres-db:
#       image: postgres:14.2-alpine
#       ports:
#         - 5432:5432
#       env:
#         POSTGRES_DB: locked_out
#         POSTGRES_USER: admin
#         POSTGRES_PASSWORD: admin
#       options: >-
#         --health-cmd pg_isready
#         --health-interval 10s
#         --health-timeout 5s
#         --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Integration Tests
        working-directory: ./identity-service
        run: ./gradlew integrationTest

  build_and_push_image:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [unit_tests, integration_tests]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build and Push the Docker image
      working-directory: ./identity-service
      run: |
        timestamp=$(TZ="Europe/London" date +'%Y%m%d%H%M')
        tag="v$timestamp"
        docker build . --file Dockerfile --tag abulsy3d/locked-out-identity-service:$tag
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u abulsy3d --password-stdin
        docker push abulsy3d/locked-out-identity-service:$tag
