name: identity-service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'identity-service/**'
  pull_request:
#    branches: [ "main" ]
    paths:
      - 'identity-service/**'

jobs:
  context:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.context.outputs.commit_sha }}
      pr_label: ${{ steps.context.outputs.pr_label }}

    steps:
      - name: Set PR label and commit SHA
        id: context
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "commit_sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
            echo "pr_label=PR-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          else
            echo "commit_sha=${{ github.sha }}" >> $GITHUB_OUTPUT
            echo "pr_label=main" >> $GITHUB_OUTPUT
          fi

      - name: Run init message
        run: |
          echo "Running Identity Service CI/CD for: ${{ steps.context.outputs.pr_label }}, commit: ${{ steps.context.outputs.commit_sha }}"

  tests:
    needs: [context]
    uses: ./.github/workflows/run-backend-tests.yml
    with:
      working-directory: ./identity-service
      test-report-artifact-name: Identity-Service-Test-Reports-${{ needs.context.outputs.pr_label }}

#  build_and_push_image:
#    if: ${{ github.event_name == 'push' }}
#    runs-on: ubuntu-latest
#    needs: [unit_tests, integration_tests, functional_tests, contract_tests]
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
#    - name: Build and Push the Docker image
#      working-directory: ./identity-service
#      run: |
#        timestamp=$(TZ="Europe/London" date +'%Y%m%d%H%M')
#        tag="v$timestamp"
#        docker build . --file Dockerfile --tag abulsy3d/locked-out-identity-service:$tag
#        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u abulsy3d --password-stdin
#        docker push abulsy3d/locked-out-identity-service:$tag
