name: identity-service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'identity-service/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Push the Docker image
      working-directory: ./identity-service
      run: |
        timestamp=$(TZ="Europe/London" date -u +'%Y%m%d%H%M')
        tag="v$timestamp"
        docker build . --file Dockerfile --tag abulsy3d/locked-out-identity-service:$tag
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u abulsy3d --password-stdin
        docker push abulsy3d/locked-out-identity-service:$tag
